name: manylinux
on: [push, pull_request]
jobs:
  manylinux:
    runs-on: ubuntu-latest
    env:
      # python-xmlsec is not compatible with xmlsec1 v1.3.3.
      # So we need to use the rc until the next release.
      # TODO: Remove it when xmlsec1 v1.3.4 is fully released.
      PYXMLSEC_XMLSEC1_VERSION: "1.3.4-rc1"
    strategy:
      matrix:
        python-abi: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310, cp311-cp311]
        image:
          - manylinux2014_x86_64
          - manylinux_2_28_x86_64
          - musllinux_1_1_x86_64
    container: quay.io/pypa/${{ matrix.image }}
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade pip setuptools wheel build
      - name: Set environment variables
        shell: bash
        run: |
          echo "PKGVER=$(/opt/python/${{ matrix.python-abi }}/bin/python setup.py --version)" >> $GITHUB_ENV
      - name: Build linux_x86_64 wheel
        env:
          PYXMLSEC_STATIC_DEPS: true
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/python -m build
      - name: Label manylinux wheel
        run: |
          ls -la dist/
          auditwheel show dist/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-linux_x86_64.whl
          auditwheel repair dist/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-linux_x86_64.whl
          ls -la wheelhouse/
          auditwheel show wheelhouse/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-*${{ matrix.image }}*.whl
      - name: Install test dependencies
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade -r requirements-test.txt
          /opt/python/${{ matrix.python-abi }}/bin/pip install xmlsec --only-binary=xmlsec --no-index --find-links=wheelhouse/
      - name: Run tests
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pytest -v --color=yes
