name: manylinux
on: [push, pull_request]
jobs:
  pep513:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-abi: [cp36-cp36m, cp37-cp37m, cp38-cp38, cp39-cp39, cp310-cp310]
        image:
          - manylinux2010_x86_64
          - manylinux_2_24_x86_64
          - musllinux_1_1_x86_64
        exclude:
          - image: manylinux2010_x86_64
            python-abi: cp310-cp310
          - image: manylinux2010_i686
            python-abi: cp310-cp310
    container: quay.io/pypa/${{ matrix.image }}
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: |
          # https://github.com/actions/runner/issues/2033
          chown -R $(id -u):$(id -g) $PWD
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade pip setuptools wheel build
      - name: Set environment variables
        shell: bash
        run: |
          echo "PKGVER=$(/opt/python/${{ matrix.python-abi }}/bin/python setup.py --version)" >> $GITHUB_ENV
      - name: Build linux_x86_64 wheel
        env:
          PYXMLSEC_STATIC_DEPS: true
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/python -m build
      - name: Label manylinux wheel
        run: |
          ls -la dist/
          auditwheel show dist/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-linux_x86_64.whl
          auditwheel repair dist/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-linux_x86_64.whl
          ls -la wheelhouse/
          auditwheel show wheelhouse/xmlsec-${{ env.PKGVER }}-${{ matrix.python-abi }}-*${{ matrix.image }}*.whl
      - name: Install test dependencies
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pip install --upgrade -r requirements-test.txt
          /opt/python/${{ matrix.python-abi }}/bin/pip install xmlsec --only-binary=xmlsec --no-index --find-links=wheelhouse/
      - name: Run tests
        run: |
          /opt/python/${{ matrix.python-abi }}/bin/pytest -v --color=yes
